AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - data/**/*
    - reports/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 140
